### ISSUE TITLE
У Серёги какая-то ошибка вылетала. 

### ISSUE THREAD

**Issue by vovets1** [mfdteam/MagicArena#135]

**Comment by andreus791** [comment]
Пусть Серега свой стилус фиксит, это из-за мультитача.

**Comment by vovets1** [comment]
У меня тоже вылетала. Репорт отправил

**Comment by andreus791** [comment]
Проверял у себя на компе и ноуте, плюс на нескольких ноутах друзей/знакомых - все ок)

**Comment by andreus791** [comment]
связано с железом/драйверами скорее всего.
