### ISSUE TITLE
Руна "Кровь за кровь", возвращающая урон/негативный эффект тому, кто пытался убить/наложить эффект на жертву.

### ISSUE THREAD

**Issue by andreus791** [mfdteam/MagicArena#143]

**Comment by vovets1** [comment]
Идея хороша, но сразу 2 руны в 1 релизе делать не надо.

**Comment by andreus791** [comment]
Согласен. Но можно реализовать, но не включать ее появление, как это было с ДД)

**Comment by vovets1** [comment]
Я кстати немного засомневался в такой руне.
