### ISSUE TITLE
Нормальный дебаг мод с возможностью выбора героя для каждого игрока (или хотя бы по сторонам)

### ISSUE THREAD

**Issue by andreus791** [mfdteam/MagicArena#144]

**Comment by vovets1** [comment]
Который позволяет брать ИИ только с 1 и 5 локи, и в случае отсутствия выбора флажком вызывал бы по обычной схеме. В таком виде можно его и в релизе оставить

**Comment by andreus791** [comment]
Можно и так, а можно в дополнение сделать и выбор зрителем для игр ИИ 4х4

**Comment by vovets1** [comment]
Да в общем-то выполнено, закрываю
