### ISSUE TITLE
Учёт киллов, сделанных зомбарями и иллюзиями 

### ISSUE THREAD

**Issue by vovets1** [mfdteam/MagicArena#148]

**Comment by andreus791** [comment]
Технически сложно из-за стяжек гравитацией и нитками, при которых происходит хаотическое перемещение с киллом прежнего юнита.

**Comment by vovets1** [comment]
Немного не понял причём тут зомби и иллюзии.

**Comment by andreus791** [comment]
Все при том же. Стяжка же перемещает их?

**Comment by andreus791** [comment]
Стяжку так и не посмотрели...
