### ISSUE TITLE
Дабы не путать киллы и хп, то стоит их разделить. Пусть хп отображается как и было, а киллы ниже (можно кстати оба пункта поместить под спойлер)

### ISSUE THREAD

**Issue by vovets1** [mfdteam/MagicArena#150]

**Comment by andreus791** [comment]
Спойлеров как таковых нет, а кнопочка над текстом скрывает все.
Как вариант - сделать переключение между страницами текста через починку/доставку опр. здания, как на карте The Maze.

**Comment by vovets1** [comment]
Тогда пусть в основной инфе о команде будут указаны ники, герой, хп (как сейчас) + возможность репика (поставить лучше после имени героя), а киллы сделать ниже
