### ISSUE TITLE
Игры разума против ИИ в дебаг моде работают некорректно

### ISSUE THREAD

**Issue by andreus791** [mfdteam/MagicArena#192]
Герои просто могут не появиться после игр)

**Comment by vovets1** [comment]
Да и фиг с ним

**Comment by vovets1** [comment]
Дебаг мод - чисто наше, игры разума плохо работают с теми ИИ, которых нет в игре, аля пех. Так что закрываю

**Comment by andreus791** [comment]
Связано с #439
