### ISSUE TITLE
Исчезновение и копирование ИИ героев

### ISSUE THREAD

**Issue by andreus791** [mfdteam/MagicArena#24]

**Comment by vovets1** [comment]
Очень может быть, что будет пофикшено в релизе после разведа, когда мы сделаем перелёт для ИИ в спец точки на время каста их скиллов

**Comment by andreus791** [comment]
Коммит №177 должен фиксить и эту хрень.

**Comment by andreus791** [comment]
Вроде все. Фикс №185. 5 ИИ игр - ни одного исчезания)
