### ISSUE TITLE
Неправильно работают показатели кд после игр разума

### ISSUE THREAD

**Issue by Sertask** [mfdteam/MagicArena#32]

**Comment by vovets1** [comment]
Кд сходят с ума, надо дальше фиксить.

**Comment by Sertask** [comment]
Кд сходят с ума только у ваги или бандита, если он своровал игры разума. У остальных же героев все нормально...

**Comment by Sertask** [comment]
Сейчас вага пофикшена. Остался только бандит с играми разума. Я думаю, что этот баг можно отнести к багу самого бандита, поэтому закрываю...
