### ISSUE TITLE
Эффекты плохо отображаются

### ISSUE THREAD

**Issue by vovets1** [mfdteam/MagicArena#387]
Спокойно может быть так, что половину времени действия того же фира под ним нет белого тайла

**Comment by vovets1** [comment]
Ничего не изменилось

**Comment by Sertask** [comment]
Если 2 игрока стоят рядом, то у одного пропадает тайл эффекта (Например, игроки со 2 локации и с 6 локации - пропадает всегда у игрока со 2 локации, если подойти к игроку с 6 локации)
