### ISSUE TITLE
Достижения

### ISSUE THREAD

**Issue by andreus791** [mfdteam/MagicArena#436]

**Comment by vovets1** [comment]
Вроде здорово, но не хочется, чтобы игроки отвлекались от игры на ачивки ("Эй, ты чего одних зобмов валишь, иди меча убей!" "Да ща, ещё 20 зомбов, у меня ачивка просто"), или же подстраивали игру под ачивки (не убивать врага в выгодной ситуации чтобы рампажку получить). К тому же в каждой игре эти ачивки заного получать. А делать так, чтобы эти ачивки что-то давали взамен - это не, всё же не квест игра.

**Comment by andreus791** [comment]
Вместо них лучше статистику
