### ISSUE TITLE
Переработка пеха (какая там по счёту?) 

### ISSUE THREAD

**Issue by vovets1** [mfdteam/MagicArena#464]
Суть в чём: убрать кулдаун на умении Оборотень. Теперь Пех сможет в любой момент сменить форму. Задержку в секунду наверное оставить. Кулдаун хила изменить с 60 до 150. Сохранять кулдауны при смене формы, разумеется. Руна перезарядки перезарядит умения сразу двух образов

**Comment by andreus791** [comment]
пока хз как сделать принудительную обратную смену образа из ваги в пеха
