### ISSUE TITLE
Оборотень: Пеха навсегда остается Вагой, причем таймер Оборотоня исчезает

### ISSUE THREAD

**Issue by andreus791** [mfdteam/MagicArena#58]

**Comment by mfdteam** [comment]
Строка №4512 на данный момент:

      Players[P].HeroType := 27;
      Players[P].TempHeroType := 27;

TempHeroType вроде как первоначальный тип героя. Нафига его снова делать вагой?)

Как вариант, если надо и на пеху, и на бандита, и еще куда-то:

      Players[P].TempHeroType := Players[P].HeroType;
      Players[P].HeroType := 27;

**Comment by vovets1** [comment]
Как багало, так и багает. Открываю

**Comment by vovets1** [comment]
После игр разума подразумевается
