### ISSUE TITLE
Баланс, баланс, баланс и еще раз баланс.

### ISSUE THREAD

**Issue by andreus791** [mfdteam/MagicArena#63]

**Comment by vovets1** [comment]
Сначала исправим баги, а потом и баланс подкорректируем

**Comment by vovets1** [comment]
Предлагаю немного ослабить Рыцаря, а именно увеличить время подготовки с 2.2 до 3 секунд, и увеличить кд до 20 секунд.

**Comment by andreus791** [comment]
сделано

**Comment by vovets1** [comment]
Предлагаю снизить дилей на "Снайперском выстреле" на 0,3 секунды

**Comment by andreus791** [comment]
запилено

**Comment by vovets1** [comment]
Предлагаю понизить кд рывка рыцаря с 20 до 18 секунд

**Comment by vovets1** [comment]
Закрою данный пункт, лучше каждое изменение записывать отдельно или несколько в 1 исью.
