### ISSUE TITLE
Лог плодит ошибки типа States.UnitPositionY: -1. Нужно что-то делать.

### ISSUE THREAD

**Issue by andreus791** [mfdteam/MagicArena#94]

**Comment by vovets1** [comment]
скорей всего именно из-за этого и садится фпс от каста игр разума

**Comment by andreus791** [comment]
вполне. и связано это, как вчера выяснили, с играми разума (а именно - с исчезанием)

**Comment by andreus791** [comment]
дополнение: 1 строка летит с концентрации пикинера

**Comment by vovets1** [comment]
Всё пофиксицца. С такой хнёй релиз нельзя.

**Comment by vovets1** [comment]
ИИ тоже их плодит

**Comment by vovets1** [comment]
Развед и ии недозапилены. После этого можно будет закрыть =)
