### ISSUE TITLE
Запилить специальные точки-нычки для мигающих героев, чтобы координаты не конфликтовали с возвратом с трибун при смерти и перемещении нитками. Иначе выходит 2х спавн героя (на скрипт не влияет, но выглядит странно)

### ISSUE THREAD

**Issue by andreus791** [mfdteam/MagicArena#98]
При разработке рыцаря был такой баг: если рыцарь умирает сразу за кастом ниток и перемещается на трибуны, жертва перемещается к нему, а вернуться не может. Мы это фиксили перемещением героя на респу. Так вот фикс коммита №122 конфликтует с этой штукой и дает 2х спавн.

**Comment by vovets1** [comment]
На новой карте и сделаем.
